sudo: required
services:
  - docker
before_install:
  - docker build -t avvinsxx/docker-react -f Dockerfile.dev .
script:
  - docker run avvinsxx/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-318281456618"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWC_ACCESS_KEY
  secret_access_key:
    secure: "$AWC_SECRET_KEY"
